- name: setup-ec2-jenkins-slave
  hosts: ec2
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenJDK 17
      apt:
        name:
          - openjdk-17-jdk
        state: present

    - name: Install Docker (Engine + CLI + containerd)
      apt:
        name:
          - docker.io
        state: present

    - name: Add ubuntu user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install required packages for Terraform
      apt:
        name:
          - wget
          - unzip
        state: present

    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
        dest: /tmp/terraform.zip

    - name: Unzip Terraform binary
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Ensure terraform binary is executable
      file:
        path: /usr/local/bin/terraform
        mode: '0755'
        state: file


